name: Courier Live Simulation

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:

  run-live-simulation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install -r requirements.txt

      - name: Create .env
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env

      - name: Run Live Simulation
        run: |
          python courier_simulation.py
